name: Purge
on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  purge:
      name: purge
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: sudo apt-get update
        - run: sudo apt-get install --yes --no-install-recommends postgresql-client
        - run: sudo systemctl stop postgresql.service
        - run: |
            flyctl proxy 5432 -a semanteilay-server-db >/dev/null 2>&1 &
            sleep 5
            psql -U postgres -h localhost -p 5432 semanteilay-server-db -f scripts/delete-rooms.sql
            psql -U postgres -h localhost -p 5432 semanteilay-server-db -f scripts/invalidate.sql
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
