name: Purge
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  purge:
      name: purge
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: apt-get update
        - run: apt-get install --yes --no-install-recommends postgresql-client
        - run: systemctl stop postgresql.service
        - run: flyctl proxy 5432 -a semanteilay-server-db
        - run: psql -U postgres -h localhost -p 5432 semanteilay-server-db -f scripts/delete-rooms.sql
        - run: psql -U postgres -h localhost -p 5432 semanteilay-server-db -f scripts/invalidate.sql
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
