name: Purge
on:
  push:
    branches:
      - dev
env:
  DATABASE_URL: ${{ secrets.FLYIO_DATABASE_URL }}
jobs:
  purge:
      name: purge
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16
        - run: npm i prisma
        - run: npx prisma db execute --file scripts/delete-rooms.sql --url="$DATABASE_URL"
        - run: npx prisma db execute --file scripts/invalidate.sql --url="$DATABASE_URL"
